<?php
namespace AtansLogger;

$title = $this->translate('Event log', __NAMESPACE__);
$this->headTitle($title);

$pagination = '';
if (count($this->paginator)) {
    $pagination =  $this->paginationControl(
        $this->paginator,
        'Sliding',
        'pagination/query',
        array(
            'route' => 'atanslogger/event',
            'options' => array(
                'query' => $form->getData(),
            ),
        )
    );
}

?>

<h4 class="page-header">
    <?php echo $this->escapeHtml($title) ?>
</h4>

<div class="panel panel-default">
    <?php if (count($paginator) > 0): ?>
        <div class="panel-body">
            <?php echo $this->render('atans-logger/event/search-form', array('form' => $form)) ?>
        </div>

        <?php echo $this->render('atans-logger/event/table', array(
            'paginator'         => $paginator,
            'isXmlHttpRequest'  => $isXmlHttpRequest,
        ))?>

    <?php else: ?>
        <div class="panel-body">
            <?php echo $this->render('atans-logger/event/search-form', array('form' => $form)) ?>
            <br>

            <div class="alert alert-info">
                <?php echo $this->translate('Could not find any logs', __NAMESPACE__) ?>
            </div>
        </div>
    <?php endif ?>
</div>

<?php echo $pagination ; ?>