<?php
namespace AtansLogger;

$title = $this->translate('Event log', __NAMESPACE__);
$this->headTitle($title);

$pagination = '';
if (count($this->paginator)) {
    $pagination =  $this->paginationControl(
        $this->paginator,
        'Sliding',
        'pagination/query',
        array(
            'route' => 'atanslogger/event',
            'options' => array(
                'query' => $form->getData(),
            ),
        )
    );
}

?>

<h4 class="page-header">
    <?php echo $this->escapeHtml($title) ?>
</h4>

<?php echo $pagination ; ?>
<div class="panel panel-default">
    <?php if (count($paginator) > 0): ?>
        <div class="panel-body">
            <?php echo $this->render('atans-logger/event/search-form', array('form' => $form)) ?>
        </div>

        <table class="table">
            <thead>
            <tr>
                <th class="col-lg-1 col-md-1 col-sm-1">#</th>
                <th class="col-lg-3 col-md-3 col-sm-3">
                    <?php echo $this->translate('Event', __NAMESPACE__) ?>
                </th>
                <th class="col-lg-5 col-md-5 col-sm-5">
                    <?php echo $this->translate('Message', __NAMESPACE__) ?>
                </th>
                <th class="col-lg-2 col-md-2 col-sm-2">
                    <?php echo $this->translate('Ip address', __NAMESPACE__) ?>
                </th>
                <th class="col-lg-2 col-md-2 col-sm-2">
                    <?php echo $this->translate('Creator', __NAMESPACE__) ?>
                </th>
            </tr>
            </thead>
            <?php
            foreach ($paginator as $event){
                echo $this->partial('atans-logger/event/partial', array('event' => $event));
            }
            ?>
        </table>
    <?php else: ?>
        <div class="panel-body">
            <?php echo $this->render('atans-logger/event/search-form', array('form' => $form)) ?>
            <br>

            <div class="alert alert-info">
                <?php echo $this->translate('Could not find any logs', __NAMESPACE__) ?>
            </div>
        </div>
    <?php endif ?>
</div>

<?php echo $pagination ; ?>