<?php
namespace AtansLogger;
?>
<tr>
    <td>
        <?php echo $this->escapeHtml($event->getId()) ?>
    </td>
    <td>
        <?php echo $this->translate('Creator', __NAMESPACE__) ?>:
        <?php if ($createdBy = $event->getCreatedBy()): ?>
            <a href="<?php echo $this->url('atanslogger/event', array(), array('query' => array('target' => $event->getTarget(), 'createdBy' => $createdBy->getId())))?>">
                <?php echo $this->escapeHtml($createdBy->getUsername()) ?>
            </a>
        <?php else: ?>
            <?php if ($username = $event->getUsername()): ?>
                <?php echo $this->escapeHtml($username) ?>
            <?php else: ?>
                <?php echo $this->translate('None', __NAMESPACE__) ?>
            <?php endif ?>
        <?php endif ?>
        <br>
        <?php echo $this->translate('Ip address', __NAMESPACE__) ?>:
        <?php echo $this->escapeHtml($event->getIpAddress()) ?>
        <br>
        <?php echo $this->translate('Date', __NAMESPACE__) ?>:
        <?php echo $this->escapeHtml($event->getCreated()->format('Y/m/d H:i:s')) ?>
        <br>
        <?php echo $this->translate('Event target', __NAMESPACE__) ?>:
        <?php echo $this->escapeHtml($event->getTarget()) ?>
        <br>
        <?php echo $this->translate('Event name', __NAMESPACE__) ?>:
        <?php echo $this->escapeHtml($event->getName()) ?>
        <br>
        <?php if ($event->getObjectId() > 0) : ?>
            <?php echo $this->translate('Object id', __NAMESPACE__) ?>:
            <a href="<?php echo $this->url('atanslogger/event', array(), array('query' => array('target' => $event->getTarget(), 'objectId' => $event->getObjectId())))?>">
                <?php echo $this->escapeHtml($event->getObjectId()) ?>
            </a>
        <?php endif ?>
    </td>
    <td>
        <?php echo nl2br($this->escapeHtml($event->getMessage())) ?>
    </td>
</tr>