<?php
use AtansLogger\Module;

/**
 * @var \Zend\Form\Form $form
 */
$form = $this->form;
$form->setAttribute('action', $this->url('atanslogger/event'));
$form->prepare();
?>
<?php echo $this->form()->openTag($form) ?>
    <div class="form-group">
        <div class="input-group">
            <div class="input-group-addon">
                <?php echo $this->translate('Count per page', Module::TRANSLATOR_TEXT_DOMAIN) ?>
            </div>
            <?php echo $this->formInput($form->get('count')) ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $this->formSelect($form->get('target')) ?>
    </div>

    <?php if ($form->get('target')->getValue()): ?>
    <div class="form-group">
        <?php echo $this->formSelect($form->get('name')) ?>
    </div>
    <?php endif ?>

    <div class="form-group">
        <div class="input-group">
            <div class="input-group-addon">
                <?php echo $this->translate('Object id', Module::TRANSLATOR_TEXT_DOMAIN) ?>
            </div>
            <?php echo $this->formInput($form->get('objectId')) ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $this->formElement($form->get('createdBy')) ?>
    </div>

    <div class="form-group">
        <div class="input-group">
            <?php echo $this->formInput($form->get('query')) ?>
            <div class="input-group-btn">
                <button class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </div>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>