<?php
namespace AtansLogger;

/**
 * @var \Zend\Paginator\Paginator $paginator
 */
$paginator = $this->paginator;

$isXmlHttpRequest = $this->isXmlHttpRequest;
?>

<?php if (! $isXmlHttpRequest || ($isXmlHttpRequest && $paginator->getCurrentPageNumber() < 2)): ?>
<table class="table table-striped">
    <thead>
    <tr>
        <th class="col-lg-1 col-md-1 col-sm-1">#</th>
        <th class="col-lg-5 col-md-5 col-sm-5">
            <?php echo $this->translate('Event', __NAMESPACE__) ?>
        </th>
        <th class="col-lg-6 col-md-6 col-sm-6">
            <?php echo $this->translate('Message', __NAMESPACE__) ?>
        </th>
    </tr>
    </thead>
<?php endif ?>

    <?php if (count($paginator) > 0) : ?>
        <?php
        foreach ($paginator as $event){
            echo $this->render('atans-logger/event/partial', array('event' => $event));
        }
        ?>
    <?php else: ?>
        <?php if ($isXmlHttpRequest): ?>
        <tr>
            <td colspan="3" class="text-center">
                <?php echo $this->translate('Could not find any logs', __NAMESPACE__) ?>
            </td>
        </tr>
        <?php endif ?>
    <?php endif ?>

<?php if (! $isXmlHttpRequest || ($isXmlHttpRequest && $paginator->getCurrentPageNumber() < 2)): ?>
</table>
<?php endif ?>