<?php
namespace AtansLogger;

$title = $this->translate('Error log', __NAMESPACE__);
$this->headTitle($title);

$pagination = '';
if (count($this->paginator)) {
    $pagination =  $this->paginationControl(
        $this->paginator,
        'Sliding',
        'pagination/query',
        array(
            'route' => 'atanslogger/error',
            'options' => array(
                'query' => $form->getData(),
            ),
        )
    );
}

?>

<h4 class="page-header">
    <?php echo $this->escapeHtml($title) ?>
</h4>

<?php echo $pagination ; ?>
<div class="panel panel-default">
    <?php if (count($paginator) > 0): ?>
        <div class="panel-body">
            <?php echo $this->render('atans-logger/error/search-form', array('form' => $form)) ?>
        </div>

        <table class="table">
            <thead>
            <tr>
                <th class="col-lg-1 col-md-1 col-sm-1">#</th>
                <th class="col-lg-11 col-md-11 col-sm-11"><?php echo $this->translate('Error', __NAMESPACE__) ?></th>
            </tr>
            </thead>
            <?php
            foreach ($paginator as $log){
                echo $this->partial('atans-logger/error/partial', array('log' => $log, 'loggerPriorities' => $this->loggerPriorities));
            }
            ?>
        </table>
    <?php else: ?>
        <div class="panel-body">
            <?php echo $this->render('atans-logger/error/search-form', array('form' => $form)) ?>
            <br>

            <div class="alert alert-info">
                <?php echo $this->translate('Could not find any logs', __NAMESPACE__) ?>
            </div>
        </div>
    <?php endif ?>
</div>

<?php echo $pagination ; ?>