<?php
use AtansLogger\Module;

/**
 * @var \AtansLogger\Entity\Error $log
 */
$log = $this->log;
$date = new \DateTime($log->getDate());

$priority = isset($loggerPriorities[$log->getPriority()]) ?  $loggerPriorities[$log->getPriority()] : 'UNKNOWN';
?>

<tr>
    <td>
        <?php echo $this->escapeHtml($log->getId()) ?>
    </td>
    <td>
        <label class="label label-danger"><?php echo $this->escapeHtml($priority) ?></label>
        <p>
            <small>
                <?php echo $this->translate('Date', Module::TRANSLATOR_TEXT_DOMAIN) ?>: <?php echo $date->format('Y/m/d H:i:s') ?><br>
                <?php echo $this->translate('File', Module::TRANSLATOR_TEXT_DOMAIN) ?>: <?php echo $this->escapeHtml($log->getFile()) ?><br>
                <?php echo $this->translate('Line', Module::TRANSLATOR_TEXT_DOMAIN) ?>: <?php echo $this->escapeHtml($log->getLine()) ?><br>
                <?php echo $this->translate('Message', Module::TRANSLATOR_TEXT_DOMAIN) ?>: <?php echo $this->escapeHtml($log->getMessage()) ?>
            </small>
        </p>

        <?php if ($trace = $log->getTrace()): ?>
        <blockquote>
            <?php echo nl2br($this->escapeHtml($trace)) ?>
        </blockquote>
        <?php endif ?>
    </td>
</tr>