<?php
namespace AtansLogger;

/**
 * @var \Zend\Form\Form $form
 */
$form = $this->form;
$form->setAttribute('action', $this->url('atanslogger/error'));
$form->prepare();
?>
<?php echo $this->form()->openTag($form) ?>
    <div class="form-group">
        <div class="input-group">
            <div class="input-group-addon">
                <?php echo $this->translate('Count per page', __NAMESPACE__) ?>
            </div>
            <?php echo $this->formInput($form->get('count')) ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $this->formSelect($form->get('priority')) ?>
    </div>

    <div class="form-group">
        <div class="input-group">
            <?php echo $this->formInput($form->get('query')) ?>
            <div class="input-group-btn">
                <button class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </div>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>